# Generated by Django 2.0.5 on 2018-05-30 03:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('request_title', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable'), ('COMPLETED', 'completed'), ('REMOVED', 'removed')], default='AVAILABLE', max_length=9)),
                ('category', models.CharField(choices=[('OTHERS', 'others'), ('PERSONAL', 'personal'), ('FAMILY', 'family'), ('WORK', 'work'), ('SCHOOL', 'school'), ('RELATIONSHIP', 'relationship')], default='OTHERS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'rejected'), ('a', 'approved')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('appeal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='livestream.Appeal')),
            ],
        ),
    ]
