# Generated by Django 2.0.5 on 2018-05-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_auto_20180511_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttoken',
            old_name='session_id',
            new_name='session',
        ),
    ]
