# Generated by Django 2.0.5 on 2018-05-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_auto_20180516_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
