# Generated by Django 2.0.5 on 2018-05-21 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_auto_20180518_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
