# Generated by Django 2.0.5 on 2018-06-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_auto_20180531_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='livestream.Appeal'),
        ),
    ]
