# Generated by Django 2.0.5 on 2018-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_auto_20180601_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('u', 'unavailable'), ('c', 'completed'), ('r', 'removed')], default='a', max_length=1),
        ),
    ]
