# Generated by Django 2.0.5 on 2018-06-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0005_notification'),
        ('livestream', '0005_auto_20180604_0817'),
    ]

    operations = [
    ]
