# Generated by Django 2.0.5 on 2018-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0006_merge_20180605_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
