# Generated by Django 2.0.5 on 2018-05-24 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0006_auto_20180523_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
