# Generated by Django 2.0.5 on 2018-05-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0007_auto_20180524_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='category',
            field=models.CharField(choices=[('OTHERS', 'others'), ('PERSONAL', 'personal'), ('FAMILY', 'family'), ('WORK', 'work'), ('SCHOOL', 'school'), ('RELATIONSHIP', 'relationship')], default='OTHERS', max_length=20),
        ),
    ]
