# Generated by Django 2.0.5 on 2018-05-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0007_auto_20180524_0207'),
        ('livestream', '0004_auto_20180521_0311'),
    ]

    operations = [
    ]
