# Generated by Django 2.0.5 on 2018-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0008_rating_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='category',
        ),
        migrations.AddField(
            model_name='appeal',
            name='category',
            field=models.ManyToManyField(to='livestream.Category'),
        ),
    ]
