# Generated by Django 2.0.5 on 2018-05-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0008_appeal_category'),
        ('livestream', '0008_merge_20180525_0328'),
    ]

    operations = [
    ]
