# Generated by Django 2.0.5 on 2018-06-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0008_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='detail',
            field=models.TextField(max_length=500),
        ),
    ]
