# Generated by Django 2.0.5 on 2018-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0009_merge_20180526_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='is_active',
        ),
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'inactive'), ('ACTIVE', 'active'), ('COMPLETED', 'completed')], default='INACTIVE', max_length=9),
        ),
    ]
