# Generated by Django 2.0.5 on 2018-05-29 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0010_auto_20180529_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestream.Appeal')),
            ],
        ),
    ]
