# Generated by Django 2.0.5 on 2018-05-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0010_auto_20180528_0652'),
        ('livestream', '0009_merge_20180526_0508'),
    ]

    operations = [
    ]
