# Generated by Django 2.0.5 on 2018-06-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0009_auto_20180609_1748'),
        ('livestream', '0010_auto_20180609_1520'),
    ]

    operations = [
    ]
