# Generated by Django 2.0.5 on 2018-05-30 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0013_auto_20180529_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='livestream.Appeal'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
