# Generated by Django 2.0.5 on 2018-05-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
